# Comment that will be sent if an issue is judged to be closed.
comment: "This issue is closed because it does not meet our issue template. Please read and follow it when submitting a new request."
issueConfigs:
# There can be several configs for different kind of issues.
- content:
# bug report
  - "Steps to reproduce:"
  - "Expected behavior:"
  - "Current behavior:"
  - "Steps to reproduce"
  - "Detailed Description"
- content:
# email add request 
  - "defund"
  - "I am a resident of"
  - "YOUR NAME"
  - "YOUR EMAIL"
  - "YOUR PHONE NUMBER"
  - "YOUR ADDRESS"
# The issue is judged to be legal if it includes all keywords from any of these two configs.
# Or it will be closed by the app

# Optional configuration:
#
# whether the keywords are case-insensitive
# default value is false, which means keywords are case-sensitive
caseInsensitive: true

# the label that will be added when the bot close an issue
# The bot will only add a label if this property is set.
#label: "closed by bot"

# The bot will ignore any issues that are opened or reopened by the user names in exception
#exception:
#  - "username1"
#  - "username2"


