# Config for a bot that automatically closes issues if they do not conform to some simple rules
# More documentation: https://probot.github.io/apps/close-issue/

# Comment to be left on auto-closed issues
comment: "This issue is closed because it does not meet our issue template. Please follow the initial template that appears when you open a new issue. Your submission should at a minimum include at least the words 'NAME' if submitting an email request, 'Description' for a bug, 'Feature' for a feature request, or 'Triage' for a triage access request"
issueConfigs:
# There can be several configs for different kind of issues.
- content:
# bug report
  - "Description"
- content:
# email add request 
  - "NAME"
- content:
# feature 
  - "Feature"
- content:
# triage 
  - "Triage"
# The issue is judged to be legal if it includes all keywords from any of these configs.
# Or it will be closed by the app

# Optional configuration:
#
# whether the keywords are case-insensitive
# default value is false, which means keywords are case-sensitive
caseInsensitive: true

# the label that will be added when the bot close an issue
# The bot will only add a label if this property is set.
#label: "closed by bot"

# The bot will ignore any issues that are opened or reopened by the user names in exception
#exception:
#  - "username1"
#  - "username2"
